'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("kadai36.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 28101,658,6580000,ﾋﾖｳｺﾞｹﾝ,ｺｳﾍﾞｼﾋｶﾞｼﾅﾀﾞｸ,ｲｶﾆｹｲｻｲｶﾞﾅｲﾊﾞｱｲ,兵庫県,神戸市東灘区,以下に掲載がない場合,0,0,0,0,0,0
        '''28101,658,6580083,ﾋﾖｳｺﾞｹﾝ,ｺｳﾍﾞｼﾋｶﾞｼﾅﾀﾞｸ,ｳｵｻﾞｷﾅｶﾏﾁ,兵庫県,神戸市東灘区,魚崎中町,0,0,1,0,0,0
        '''28101,658,6580026,ﾋﾖｳｺﾞｹﾝ,ｺｳﾍﾞｼﾋｶﾞｼﾅﾀﾞｸ,ｳｵｻﾞｷﾆｼﾏﾁ,兵庫県,神戸市東灘区,魚崎西町,0,0,1,0,0,0
        '''28101,658,6580025,ﾋﾖｳｺﾞｹﾝ,ｺｳﾍﾞｼﾋｶﾞｼﾅﾀﾞｸ,ｳｵｻﾞｷﾐﾅﾐﾏﾁ,兵庫県,神戸市東灘区,魚崎南町,0,0,1,0,0,0
        '''28101,658,6580082,ﾋﾖｳｺﾞｹﾝ,ｺｳﾍﾞｼﾋｶﾞｼﾅﾀﾞｸ,ｳｵｻﾞｷｷﾀﾏﾁ,兵庫県,神戸市東灘区,魚崎北町,0,0,1,0,0,0
        '''28101,658,6580024,ﾋﾖｳｺﾞｹﾝ,ｺｳﾍﾞｼﾋｶﾞｼﾅﾀﾞｸ,ｳｵｻﾞｷﾊﾏﾏﾁ,兵庫県,神戸市東灘区,魚崎浜町,0,0,0,0,0,0
        '''28101,658,6580066,ﾋﾖｳｺﾞｹﾝ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property _28HYOGO() As String
            Get
                Return ResourceManager.GetString("28HYOGO", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
