<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="Orders.aspx.vb" Inherits="NorthwindUnleashed.Orders" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <ef:entitydatasource ID="EntityDataSource1" runat="server"
        ConnectionString="name=NorthwindEntities" 
        DefaultContainerName="NorthwindEntities"
        EntitySetName="Orders" AutoGenerateOrderByClause="True" 
        AutoGenerateWhereClause="True" EnableDelete="True" 
        EnableInsert="True" 
        EnableUpdate="True">
    </ef:entitydatasource>
<asp:TextBox ID="FilterTextBox" runat="server"></asp:TextBox>
<asp:Button ID="FilterButton" runat="server" Text="Button" />
<asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
    AllowSorting="True"
    AutoGenerateColumns="False" 
    AllowCustomPaging="true" 
    PageSize="20" 
    AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
    DataKeyNames="OrderID" 
    DataSourceID="EntityDataSource1">
    <Columns>
        <asp:CommandField ShowSelectButton="True" />
        <asp:BoundField DataField="OrderID" HeaderText="OrderID" ReadOnly="True"
     SortExpression="OrderID" />
        <asp:BoundField DataField="CustomerID" HeaderText="CustomerID"
     SortExpression="CustomerID" />
        <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID"
     SortExpression="EmployeeID" />
        <asp:BoundField DataField="OrderDate" HeaderText="OrderDate"
     SortExpression="OrderDate" />
        <asp:BoundField DataField="RequiredDate" HeaderText="RequiredDate"
     SortExpression="RequiredDate" />
        <asp:BoundField DataField="ShippedDate" HeaderText="ShippedDate"
     SortExpression="ShippedDate" />
        <asp:BoundField DataField="ShipVia" HeaderText="ShipVia"
     SortExpression="ShipVia" />
        <asp:BoundField DataField="Freight" HeaderText="Freight"
     SortExpression="Freight" />
        <asp:BoundField DataField="ShipName" HeaderText="ShipName"
     SortExpression="ShipName" />
        <asp:BoundField DataField="ShipAddress" HeaderText="ShipAddress"
     SortExpression="ShipAddress" />
        <asp:BoundField DataField="ShipCity" HeaderText="ShipCity"
     SortExpression="ShipCity" />
        <asp:BoundField DataField="ShipRegion" HeaderText="ShipRegion"
     SortExpression="ShipRegion" />
        <asp:BoundField DataField="ShipPostalCode" HeaderText="ShipPostalCode"
     SortExpression="ShipPostalCode" />
        <asp:BoundField DataField="ShipCountry" HeaderText="ShipCountry"
     SortExpression="ShipCountry" />
    </Columns>
</asp:GridView>

    <asp:QueryExtender ID="QueryExtender1" runat="server" TargetControlID="EntityDataSource1">
            <asp:SearchExpression DataFields="ShipCity" SearchType="StartsWith">
        <asp:ControlParameter ControlID="FilterTextBox" Type="String" />
    </asp:SearchExpression>

    </asp:QueryExtender>
</asp:Content>
