'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace BookServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Book", [Namespace]:="http://schemas.datacontract.org/2004/07/BookService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Book
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AuthorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatePublishedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ISBNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Author() As String
            Get
                Return Me.AuthorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuthorField, value) <> true) Then
                    Me.AuthorField = value
                    Me.RaisePropertyChanged("Author")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DatePublished() As System.Nullable(Of Date)
            Get
                Return Me.DatePublishedField
            End Get
            Set
                If (Me.DatePublishedField.Equals(value) <> true) Then
                    Me.DatePublishedField = value
                    Me.RaisePropertyChanged("DatePublished")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ISBN() As String
            Get
                Return Me.ISBNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ISBNField, value) <> true) Then
                    Me.ISBNField = value
                    Me.RaisePropertyChanged("ISBN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="BookServiceReference.IBookService")>  _
    Public Interface IBookService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBookService/ValidateBook", ReplyAction:="http://tempuri.org/IBookService/ValidateBookResponse")>  _
        Function ValidateBook(ByVal bookToValidate As BookServiceReference.Book) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBookService/ValidateBook", ReplyAction:="http://tempuri.org/IBookService/ValidateBookResponse")>  _
        Function ValidateBookAsync(ByVal bookToValidate As BookServiceReference.Book) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IBookServiceChannel
        Inherits BookServiceReference.IBookService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BookServiceClient
        Inherits System.ServiceModel.ClientBase(Of IBookService)
        Implements IBookService

        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        Public Function ValidateBook(ByVal bookToValidate As BookServiceReference.Book) As String Implements BookServiceReference.IBookService.ValidateBook
            Return MyBase.Channel.ValidateBook(bookToValidate)
        End Function

        Public Function ValidateBookAsync(ByVal bookToValidate As BookServiceReference.Book) As System.Threading.Tasks.Task(Of String) Implements BookServiceReference.IBookService.ValidateBookAsync
            Return MyBase.Channel.ValidateBookAsync(bookToValidate)
        End Function
    End Class
End Namespace
