
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute("57ff0d5c-ef46-47e8-a52c-2e86c14cc910")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("Northwind40Model", "Products_FK01", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Category), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Product), True)>
<Assembly: EdmRelationshipAttribute("Northwind40Model", "Orders_FK00", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Customer), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Order), True)>
<Assembly: EdmRelationshipAttribute("Northwind40Model", "Orders_FK02", "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Employee), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Order), True)>
<Assembly: EdmRelationshipAttribute("Northwind40Model", "Order_Details_FK00", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Product), "Order_Details", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Order_Detail), True)>
<Assembly: EdmRelationshipAttribute("Northwind40Model", "Order_Details_FK01", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Order), "Order_Details", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Order_Detail), True)>
<Assembly: EdmRelationshipAttribute("Northwind40Model", "Orders_FK01", "Shippers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Shipper), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Order), True)>
<Assembly: EdmRelationshipAttribute("Northwind40Model", "Products_FK00", "Suppliers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Supplier), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Product), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class Northwind40Entities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new Northwind40Entities object using the connection string found in the 'Northwind40Entities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Northwind40Entities", "Northwind40Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Northwind40Entities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Northwind40Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Northwind40Entities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Northwind40Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Categories() As ObjectSet(Of Category)
        Get
            If (_Categories Is Nothing) Then
                _Categories = MyBase.CreateObjectSet(Of Category)("Categories")
            End If
            Return _Categories
        End Get
    End Property

    Private _Categories As ObjectSet(Of Category)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Customers() As ObjectSet(Of Customer)
        Get
            If (_Customers Is Nothing) Then
                _Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
            End If
            Return _Customers
        End Get
    End Property

    Private _Customers As ObjectSet(Of Customer)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Employees() As ObjectSet(Of Employee)
        Get
            If (_Employees Is Nothing) Then
                _Employees = MyBase.CreateObjectSet(Of Employee)("Employees")
            End If
            Return _Employees
        End Get
    End Property

    Private _Employees As ObjectSet(Of Employee)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Order_Details() As ObjectSet(Of Order_Detail)
        Get
            If (_Order_Details Is Nothing) Then
                _Order_Details = MyBase.CreateObjectSet(Of Order_Detail)("Order_Details")
            End If
            Return _Order_Details
        End Get
    End Property

    Private _Order_Details As ObjectSet(Of Order_Detail)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Orders() As ObjectSet(Of Order)
        Get
            If (_Orders Is Nothing) Then
                _Orders = MyBase.CreateObjectSet(Of Order)("Orders")
            End If
            Return _Orders
        End Get
    End Property

    Private _Orders As ObjectSet(Of Order)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Products() As ObjectSet(Of Product)
        Get
            If (_Products Is Nothing) Then
                _Products = MyBase.CreateObjectSet(Of Product)("Products")
            End If
            Return _Products
        End Get
    End Property

    Private _Products As ObjectSet(Of Product)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Shippers() As ObjectSet(Of Shipper)
        Get
            If (_Shippers Is Nothing) Then
                _Shippers = MyBase.CreateObjectSet(Of Shipper)("Shippers")
            End If
            Return _Shippers
        End Get
    End Property

    Private _Shippers As ObjectSet(Of Shipper)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Suppliers() As ObjectSet(Of Supplier)
        Get
            If (_Suppliers Is Nothing) Then
                _Suppliers = MyBase.CreateObjectSet(Of Supplier)("Suppliers")
            End If
            Return _Suppliers
        End Get
    End Property

    Private _Suppliers As ObjectSet(Of Supplier)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCategories(ByVal category As Category)
        MyBase.AddObject("Categories", category)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCustomers(ByVal customer As Customer)
        MyBase.AddObject("Customers", customer)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToEmployees(ByVal employee As Employee)
        MyBase.AddObject("Employees", employee)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Order_Details EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOrder_Details(ByVal order_Detail As Order_Detail)
        MyBase.AddObject("Order_Details", order_Detail)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOrders(ByVal order As Order)
        MyBase.AddObject("Orders", order)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProducts(ByVal product As Product)
        MyBase.AddObject("Products", product)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Shippers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToShippers(ByVal shipper As Shipper)
        MyBase.AddObject("Shippers", shipper)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Suppliers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSuppliers(ByVal supplier As Supplier)
        MyBase.AddObject("Suppliers", supplier)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Northwind40Model", Name:="Category")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Category
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Category object.
    ''' </summary>
    ''' <param name="category_ID">Initial value of the Category_ID property.</param>
    ''' <param name="category_Name">Initial value of the Category_Name property.</param>
    Public Shared Function CreateCategory(category_ID As Global.System.Int32, category_Name As Global.System.String) As Category
        Dim category as Category = New Category
        category.Category_ID = category_ID
        category.Category_Name = category_Name
        Return category
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Category_ID() As Global.System.Int32
        Get
            Return _Category_ID
        End Get
        Set
            If (_Category_ID <> Value) Then
                OnCategory_IDChanging(value)
                ReportPropertyChanging("Category_ID")
                _Category_ID = StructuralObject.SetValidValue(value, "Category_ID")
                ReportPropertyChanged("Category_ID")
                OnCategory_IDChanged()
            End If
        End Set
    End Property

    Private _Category_ID As Global.System.Int32
    Private Partial Sub OnCategory_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCategory_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Category_Name() As Global.System.String
        Get
            Return _Category_Name
        End Get
        Set
            OnCategory_NameChanging(value)
            ReportPropertyChanging("Category_Name")
            _Category_Name = StructuralObject.SetValidValue(value, false, "Category_Name")
            ReportPropertyChanged("Category_Name")
            OnCategory_NameChanged()
        End Set
    End Property

    Private _Category_Name As Global.System.String
    Private Partial Sub OnCategory_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategory_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Description() As Global.System.String
        Get
            Return _Description
        End Get
        Set
            OnDescriptionChanging(value)
            ReportPropertyChanging("Description")
            _Description = StructuralObject.SetValidValue(value, true, "Description")
            ReportPropertyChanged("Description")
            OnDescriptionChanged()
        End Set
    End Property

    Private _Description As Global.System.String
    Private Partial Sub OnDescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Picture() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Picture)
        End Get
        Set
            OnPictureChanging(value)
            ReportPropertyChanging("Picture")
            _Picture = StructuralObject.SetValidValue(value, true, "Picture")
            ReportPropertyChanged("Picture")
            OnPictureChanged()
        End Set
    End Property

    Private _Picture As Global.System.Byte()
    Private Partial Sub OnPictureChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnPictureChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Products_FK01", "Products")>
     Public Property Products() As EntityCollection(Of Product)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Product)("Northwind40Model.Products_FK01", "Products")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Product)("Northwind40Model.Products_FK01", "Products", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Northwind40Model", Name:="Customer")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Customer
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Customer object.
    ''' </summary>
    ''' <param name="customer_ID">Initial value of the Customer_ID property.</param>
    ''' <param name="company_Name">Initial value of the Company_Name property.</param>
    Public Shared Function CreateCustomer(customer_ID As Global.System.String, company_Name As Global.System.String) As Customer
        Dim customer as Customer = New Customer
        customer.Customer_ID = customer_ID
        customer.Company_Name = company_Name
        Return customer
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Customer_ID() As Global.System.String
        Get
            Return _Customer_ID
        End Get
        Set
            If (_Customer_ID <> Value) Then
                OnCustomer_IDChanging(value)
                ReportPropertyChanging("Customer_ID")
                _Customer_ID = StructuralObject.SetValidValue(value, false, "Customer_ID")
                ReportPropertyChanged("Customer_ID")
                OnCustomer_IDChanged()
            End If
        End Set
    End Property

    Private _Customer_ID As Global.System.String
    Private Partial Sub OnCustomer_IDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomer_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Company_Name() As Global.System.String
        Get
            Return _Company_Name
        End Get
        Set
            OnCompany_NameChanging(value)
            ReportPropertyChanging("Company_Name")
            _Company_Name = StructuralObject.SetValidValue(value, false, "Company_Name")
            ReportPropertyChanged("Company_Name")
            OnCompany_NameChanged()
        End Set
    End Property

    Private _Company_Name As Global.System.String
    Private Partial Sub OnCompany_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCompany_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Contact_Name() As Global.System.String
        Get
            Return _Contact_Name
        End Get
        Set
            OnContact_NameChanging(value)
            ReportPropertyChanging("Contact_Name")
            _Contact_Name = StructuralObject.SetValidValue(value, true, "Contact_Name")
            ReportPropertyChanged("Contact_Name")
            OnContact_NameChanged()
        End Set
    End Property

    Private _Contact_Name As Global.System.String
    Private Partial Sub OnContact_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContact_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Contact_Title() As Global.System.String
        Get
            Return _Contact_Title
        End Get
        Set
            OnContact_TitleChanging(value)
            ReportPropertyChanging("Contact_Title")
            _Contact_Title = StructuralObject.SetValidValue(value, true, "Contact_Title")
            ReportPropertyChanged("Contact_Title")
            OnContact_TitleChanged()
        End Set
    End Property

    Private _Contact_Title As Global.System.String
    Private Partial Sub OnContact_TitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContact_TitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Address() As Global.System.String
        Get
            Return _Address
        End Get
        Set
            OnAddressChanging(value)
            ReportPropertyChanging("Address")
            _Address = StructuralObject.SetValidValue(value, true, "Address")
            ReportPropertyChanged("Address")
            OnAddressChanged()
        End Set
    End Property

    Private _Address As Global.System.String
    Private Partial Sub OnAddressChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, true, "City")
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property

    Private _City As Global.System.String
    Private Partial Sub OnCityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Region() As Global.System.String
        Get
            Return _Region
        End Get
        Set
            OnRegionChanging(value)
            ReportPropertyChanging("Region")
            _Region = StructuralObject.SetValidValue(value, true, "Region")
            ReportPropertyChanged("Region")
            OnRegionChanged()
        End Set
    End Property

    Private _Region As Global.System.String
    Private Partial Sub OnRegionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRegionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Postal_Code() As Global.System.String
        Get
            Return _Postal_Code
        End Get
        Set
            OnPostal_CodeChanging(value)
            ReportPropertyChanging("Postal_Code")
            _Postal_Code = StructuralObject.SetValidValue(value, true, "Postal_Code")
            ReportPropertyChanged("Postal_Code")
            OnPostal_CodeChanged()
        End Set
    End Property

    Private _Postal_Code As Global.System.String
    Private Partial Sub OnPostal_CodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPostal_CodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Country() As Global.System.String
        Get
            Return _Country
        End Get
        Set
            OnCountryChanging(value)
            ReportPropertyChanging("Country")
            _Country = StructuralObject.SetValidValue(value, true, "Country")
            ReportPropertyChanged("Country")
            OnCountryChanged()
        End Set
    End Property

    Private _Country As Global.System.String
    Private Partial Sub OnCountryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCountryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Phone() As Global.System.String
        Get
            Return _Phone
        End Get
        Set
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = StructuralObject.SetValidValue(value, true, "Phone")
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property

    Private _Phone As Global.System.String
    Private Partial Sub OnPhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Fax() As Global.System.String
        Get
            Return _Fax
        End Get
        Set
            OnFaxChanging(value)
            ReportPropertyChanging("Fax")
            _Fax = StructuralObject.SetValidValue(value, true, "Fax")
            ReportPropertyChanged("Fax")
            OnFaxChanged()
        End Set
    End Property

    Private _Fax As Global.System.String
    Private Partial Sub OnFaxChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFaxChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Orders_FK00", "Orders")>
     Public Property Orders() As EntityCollection(Of Order)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("Northwind40Model.Orders_FK00", "Orders")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("Northwind40Model.Orders_FK00", "Orders", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Northwind40Model", Name:="Employee")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Employee
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Employee object.
    ''' </summary>
    ''' <param name="employee_ID">Initial value of the Employee_ID property.</param>
    ''' <param name="last_Name">Initial value of the Last_Name property.</param>
    ''' <param name="first_Name">Initial value of the First_Name property.</param>
    Public Shared Function CreateEmployee(employee_ID As Global.System.Int32, last_Name As Global.System.String, first_Name As Global.System.String) As Employee
        Dim employee as Employee = New Employee
        employee.Employee_ID = employee_ID
        employee.Last_Name = last_Name
        employee.First_Name = first_Name
        Return employee
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Employee_ID() As Global.System.Int32
        Get
            Return _Employee_ID
        End Get
        Set
            If (_Employee_ID <> Value) Then
                OnEmployee_IDChanging(value)
                ReportPropertyChanging("Employee_ID")
                _Employee_ID = StructuralObject.SetValidValue(value, "Employee_ID")
                ReportPropertyChanged("Employee_ID")
                OnEmployee_IDChanged()
            End If
        End Set
    End Property

    Private _Employee_ID As Global.System.Int32
    Private Partial Sub OnEmployee_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnEmployee_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Last_Name() As Global.System.String
        Get
            Return _Last_Name
        End Get
        Set
            OnLast_NameChanging(value)
            ReportPropertyChanging("Last_Name")
            _Last_Name = StructuralObject.SetValidValue(value, false, "Last_Name")
            ReportPropertyChanged("Last_Name")
            OnLast_NameChanged()
        End Set
    End Property

    Private _Last_Name As Global.System.String
    Private Partial Sub OnLast_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLast_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property First_Name() As Global.System.String
        Get
            Return _First_Name
        End Get
        Set
            OnFirst_NameChanging(value)
            ReportPropertyChanging("First_Name")
            _First_Name = StructuralObject.SetValidValue(value, false, "First_Name")
            ReportPropertyChanged("First_Name")
            OnFirst_NameChanged()
        End Set
    End Property

    Private _First_Name As Global.System.String
    Private Partial Sub OnFirst_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFirst_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Title() As Global.System.String
        Get
            Return _Title
        End Get
        Set
            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, true, "Title")
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property

    Private _Title As Global.System.String
    Private Partial Sub OnTitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Birth_Date() As Nullable(Of Global.System.DateTime)
        Get
            Return _Birth_Date
        End Get
        Set
            OnBirth_DateChanging(value)
            ReportPropertyChanging("Birth_Date")
            _Birth_Date = StructuralObject.SetValidValue(value, "Birth_Date")
            ReportPropertyChanged("Birth_Date")
            OnBirth_DateChanged()
        End Set
    End Property

    Private _Birth_Date As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnBirth_DateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnBirth_DateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Hire_Date() As Nullable(Of Global.System.DateTime)
        Get
            Return _Hire_Date
        End Get
        Set
            OnHire_DateChanging(value)
            ReportPropertyChanging("Hire_Date")
            _Hire_Date = StructuralObject.SetValidValue(value, "Hire_Date")
            ReportPropertyChanged("Hire_Date")
            OnHire_DateChanged()
        End Set
    End Property

    Private _Hire_Date As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnHire_DateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnHire_DateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Address() As Global.System.String
        Get
            Return _Address
        End Get
        Set
            OnAddressChanging(value)
            ReportPropertyChanging("Address")
            _Address = StructuralObject.SetValidValue(value, true, "Address")
            ReportPropertyChanged("Address")
            OnAddressChanged()
        End Set
    End Property

    Private _Address As Global.System.String
    Private Partial Sub OnAddressChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, true, "City")
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property

    Private _City As Global.System.String
    Private Partial Sub OnCityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Region() As Global.System.String
        Get
            Return _Region
        End Get
        Set
            OnRegionChanging(value)
            ReportPropertyChanging("Region")
            _Region = StructuralObject.SetValidValue(value, true, "Region")
            ReportPropertyChanged("Region")
            OnRegionChanged()
        End Set
    End Property

    Private _Region As Global.System.String
    Private Partial Sub OnRegionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRegionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Postal_Code() As Global.System.String
        Get
            Return _Postal_Code
        End Get
        Set
            OnPostal_CodeChanging(value)
            ReportPropertyChanging("Postal_Code")
            _Postal_Code = StructuralObject.SetValidValue(value, true, "Postal_Code")
            ReportPropertyChanged("Postal_Code")
            OnPostal_CodeChanged()
        End Set
    End Property

    Private _Postal_Code As Global.System.String
    Private Partial Sub OnPostal_CodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPostal_CodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Country() As Global.System.String
        Get
            Return _Country
        End Get
        Set
            OnCountryChanging(value)
            ReportPropertyChanging("Country")
            _Country = StructuralObject.SetValidValue(value, true, "Country")
            ReportPropertyChanged("Country")
            OnCountryChanged()
        End Set
    End Property

    Private _Country As Global.System.String
    Private Partial Sub OnCountryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCountryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Home_Phone() As Global.System.String
        Get
            Return _Home_Phone
        End Get
        Set
            OnHome_PhoneChanging(value)
            ReportPropertyChanging("Home_Phone")
            _Home_Phone = StructuralObject.SetValidValue(value, true, "Home_Phone")
            ReportPropertyChanged("Home_Phone")
            OnHome_PhoneChanged()
        End Set
    End Property

    Private _Home_Phone As Global.System.String
    Private Partial Sub OnHome_PhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnHome_PhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Extension() As Global.System.String
        Get
            Return _Extension
        End Get
        Set
            OnExtensionChanging(value)
            ReportPropertyChanging("Extension")
            _Extension = StructuralObject.SetValidValue(value, true, "Extension")
            ReportPropertyChanged("Extension")
            OnExtensionChanged()
        End Set
    End Property

    Private _Extension As Global.System.String
    Private Partial Sub OnExtensionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnExtensionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Photo() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Photo)
        End Get
        Set
            OnPhotoChanging(value)
            ReportPropertyChanging("Photo")
            _Photo = StructuralObject.SetValidValue(value, true, "Photo")
            ReportPropertyChanged("Photo")
            OnPhotoChanged()
        End Set
    End Property

    Private _Photo As Global.System.Byte()
    Private Partial Sub OnPhotoChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnPhotoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Notes() As Global.System.String
        Get
            Return _Notes
        End Get
        Set
            OnNotesChanging(value)
            ReportPropertyChanging("Notes")
            _Notes = StructuralObject.SetValidValue(value, true, "Notes")
            ReportPropertyChanged("Notes")
            OnNotesChanged()
        End Set
    End Property

    Private _Notes As Global.System.String
    Private Partial Sub OnNotesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNotesChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Reports_To() As Nullable(Of Global.System.Int32)
        Get
            Return _Reports_To
        End Get
        Set
            OnReports_ToChanging(value)
            ReportPropertyChanging("Reports_To")
            _Reports_To = StructuralObject.SetValidValue(value, "Reports_To")
            ReportPropertyChanged("Reports_To")
            OnReports_ToChanged()
        End Set
    End Property

    Private _Reports_To As Nullable(Of Global.System.Int32)
    Private Partial Sub OnReports_ToChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnReports_ToChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Orders_FK02", "Orders")>
     Public Property Orders() As EntityCollection(Of Order)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("Northwind40Model.Orders_FK02", "Orders")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("Northwind40Model.Orders_FK02", "Orders", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Northwind40Model", Name:="Order")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Order
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Order object.
    ''' </summary>
    ''' <param name="order_ID">Initial value of the Order_ID property.</param>
    ''' <param name="customer_ID">Initial value of the Customer_ID property.</param>
    Public Shared Function CreateOrder(order_ID As Global.System.Int32, customer_ID As Global.System.String) As Order
        Dim order as Order = New Order
        order.Order_ID = order_ID
        order.Customer_ID = customer_ID
        Return order
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Order_ID() As Global.System.Int32
        Get
            Return _Order_ID
        End Get
        Set
            If (_Order_ID <> Value) Then
                OnOrder_IDChanging(value)
                ReportPropertyChanging("Order_ID")
                _Order_ID = StructuralObject.SetValidValue(value, "Order_ID")
                ReportPropertyChanged("Order_ID")
                OnOrder_IDChanged()
            End If
        End Set
    End Property

    Private _Order_ID As Global.System.Int32
    Private Partial Sub OnOrder_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOrder_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Customer_ID() As Global.System.String
        Get
            Return _Customer_ID
        End Get
        Set
            OnCustomer_IDChanging(value)
            ReportPropertyChanging("Customer_ID")
            _Customer_ID = StructuralObject.SetValidValue(value, false, "Customer_ID")
            ReportPropertyChanged("Customer_ID")
            OnCustomer_IDChanged()
        End Set
    End Property

    Private _Customer_ID As Global.System.String
    Private Partial Sub OnCustomer_IDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomer_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Employee_ID() As Nullable(Of Global.System.Int32)
        Get
            Return _Employee_ID
        End Get
        Set
            OnEmployee_IDChanging(value)
            ReportPropertyChanging("Employee_ID")
            _Employee_ID = StructuralObject.SetValidValue(value, "Employee_ID")
            ReportPropertyChanged("Employee_ID")
            OnEmployee_IDChanged()
        End Set
    End Property

    Private _Employee_ID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnEmployee_IDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnEmployee_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Ship_Name() As Global.System.String
        Get
            Return _Ship_Name
        End Get
        Set
            OnShip_NameChanging(value)
            ReportPropertyChanging("Ship_Name")
            _Ship_Name = StructuralObject.SetValidValue(value, true, "Ship_Name")
            ReportPropertyChanged("Ship_Name")
            OnShip_NameChanged()
        End Set
    End Property

    Private _Ship_Name As Global.System.String
    Private Partial Sub OnShip_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnShip_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Ship_Address() As Global.System.String
        Get
            Return _Ship_Address
        End Get
        Set
            OnShip_AddressChanging(value)
            ReportPropertyChanging("Ship_Address")
            _Ship_Address = StructuralObject.SetValidValue(value, true, "Ship_Address")
            ReportPropertyChanged("Ship_Address")
            OnShip_AddressChanged()
        End Set
    End Property

    Private _Ship_Address As Global.System.String
    Private Partial Sub OnShip_AddressChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnShip_AddressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Ship_City() As Global.System.String
        Get
            Return _Ship_City
        End Get
        Set
            OnShip_CityChanging(value)
            ReportPropertyChanging("Ship_City")
            _Ship_City = StructuralObject.SetValidValue(value, true, "Ship_City")
            ReportPropertyChanged("Ship_City")
            OnShip_CityChanged()
        End Set
    End Property

    Private _Ship_City As Global.System.String
    Private Partial Sub OnShip_CityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnShip_CityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Ship_Region() As Global.System.String
        Get
            Return _Ship_Region
        End Get
        Set
            OnShip_RegionChanging(value)
            ReportPropertyChanging("Ship_Region")
            _Ship_Region = StructuralObject.SetValidValue(value, true, "Ship_Region")
            ReportPropertyChanged("Ship_Region")
            OnShip_RegionChanged()
        End Set
    End Property

    Private _Ship_Region As Global.System.String
    Private Partial Sub OnShip_RegionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnShip_RegionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Ship_Postal_Code() As Global.System.String
        Get
            Return _Ship_Postal_Code
        End Get
        Set
            OnShip_Postal_CodeChanging(value)
            ReportPropertyChanging("Ship_Postal_Code")
            _Ship_Postal_Code = StructuralObject.SetValidValue(value, true, "Ship_Postal_Code")
            ReportPropertyChanged("Ship_Postal_Code")
            OnShip_Postal_CodeChanged()
        End Set
    End Property

    Private _Ship_Postal_Code As Global.System.String
    Private Partial Sub OnShip_Postal_CodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnShip_Postal_CodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Ship_Country() As Global.System.String
        Get
            Return _Ship_Country
        End Get
        Set
            OnShip_CountryChanging(value)
            ReportPropertyChanging("Ship_Country")
            _Ship_Country = StructuralObject.SetValidValue(value, true, "Ship_Country")
            ReportPropertyChanged("Ship_Country")
            OnShip_CountryChanged()
        End Set
    End Property

    Private _Ship_Country As Global.System.String
    Private Partial Sub OnShip_CountryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnShip_CountryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Ship_Via() As Nullable(Of Global.System.Int32)
        Get
            Return _Ship_Via
        End Get
        Set
            OnShip_ViaChanging(value)
            ReportPropertyChanging("Ship_Via")
            _Ship_Via = StructuralObject.SetValidValue(value, "Ship_Via")
            ReportPropertyChanged("Ship_Via")
            OnShip_ViaChanged()
        End Set
    End Property

    Private _Ship_Via As Nullable(Of Global.System.Int32)
    Private Partial Sub OnShip_ViaChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnShip_ViaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Order_Date() As Nullable(Of Global.System.DateTime)
        Get
            Return _Order_Date
        End Get
        Set
            OnOrder_DateChanging(value)
            ReportPropertyChanging("Order_Date")
            _Order_Date = StructuralObject.SetValidValue(value, "Order_Date")
            ReportPropertyChanged("Order_Date")
            OnOrder_DateChanged()
        End Set
    End Property

    Private _Order_Date As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnOrder_DateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnOrder_DateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Required_Date() As Nullable(Of Global.System.DateTime)
        Get
            Return _Required_Date
        End Get
        Set
            OnRequired_DateChanging(value)
            ReportPropertyChanging("Required_Date")
            _Required_Date = StructuralObject.SetValidValue(value, "Required_Date")
            ReportPropertyChanged("Required_Date")
            OnRequired_DateChanged()
        End Set
    End Property

    Private _Required_Date As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnRequired_DateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnRequired_DateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Shipped_Date() As Nullable(Of Global.System.DateTime)
        Get
            Return _Shipped_Date
        End Get
        Set
            OnShipped_DateChanging(value)
            ReportPropertyChanging("Shipped_Date")
            _Shipped_Date = StructuralObject.SetValidValue(value, "Shipped_Date")
            ReportPropertyChanged("Shipped_Date")
            OnShipped_DateChanged()
        End Set
    End Property

    Private _Shipped_Date As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnShipped_DateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnShipped_DateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Freight() As Nullable(Of Global.System.Decimal)
        Get
            Return _Freight
        End Get
        Set
            OnFreightChanging(value)
            ReportPropertyChanging("Freight")
            _Freight = StructuralObject.SetValidValue(value, "Freight")
            ReportPropertyChanged("Freight")
            OnFreightChanged()
        End Set
    End Property

    Private _Freight As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnFreightChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnFreightChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Orders_FK00", "Customers")>
    Public Property Customer() As Customer
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("Northwind40Model.Orders_FK00", "Customers").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("Northwind40Model.Orders_FK00", "Customers").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CustomerReference() As EntityReference(Of Customer)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("Northwind40Model.Orders_FK00", "Customers")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("Northwind40Model.Orders_FK00", "Customers", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Orders_FK02", "Employees")>
    Public Property Employee() As Employee
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Employee)("Northwind40Model.Orders_FK02", "Employees").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Employee)("Northwind40Model.Orders_FK02", "Employees").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EmployeeReference() As EntityReference(Of Employee)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Employee)("Northwind40Model.Orders_FK02", "Employees")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Employee)("Northwind40Model.Orders_FK02", "Employees", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Order_Details_FK01", "Order_Details")>
     Public Property Order_Details() As EntityCollection(Of Order_Detail)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order_Detail)("Northwind40Model.Order_Details_FK01", "Order_Details")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order_Detail)("Northwind40Model.Order_Details_FK01", "Order_Details", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Orders_FK01", "Shippers")>
    Public Property Shipper() As Shipper
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Shipper)("Northwind40Model.Orders_FK01", "Shippers").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Shipper)("Northwind40Model.Orders_FK01", "Shippers").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ShipperReference() As EntityReference(Of Shipper)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Shipper)("Northwind40Model.Orders_FK01", "Shippers")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Shipper)("Northwind40Model.Orders_FK01", "Shippers", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Northwind40Model", Name:="Order_Detail")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Order_Detail
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Order_Detail object.
    ''' </summary>
    ''' <param name="order_ID">Initial value of the Order_ID property.</param>
    ''' <param name="product_ID">Initial value of the Product_ID property.</param>
    ''' <param name="unit_Price">Initial value of the Unit_Price property.</param>
    ''' <param name="quantity">Initial value of the Quantity property.</param>
    ''' <param name="discount">Initial value of the Discount property.</param>
    Public Shared Function CreateOrder_Detail(order_ID As Global.System.Int32, product_ID As Global.System.Int32, unit_Price As Global.System.Decimal, quantity As Global.System.Int16, discount As Global.System.Single) As Order_Detail
        Dim order_Detail as Order_Detail = New Order_Detail
        order_Detail.Order_ID = order_ID
        order_Detail.Product_ID = product_ID
        order_Detail.Unit_Price = unit_Price
        order_Detail.Quantity = quantity
        order_Detail.Discount = discount
        Return order_Detail
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Order_ID() As Global.System.Int32
        Get
            Return _Order_ID
        End Get
        Set
            If (_Order_ID <> Value) Then
                OnOrder_IDChanging(value)
                ReportPropertyChanging("Order_ID")
                _Order_ID = StructuralObject.SetValidValue(value, "Order_ID")
                ReportPropertyChanged("Order_ID")
                OnOrder_IDChanged()
            End If
        End Set
    End Property

    Private _Order_ID As Global.System.Int32
    Private Partial Sub OnOrder_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOrder_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Product_ID() As Global.System.Int32
        Get
            Return _Product_ID
        End Get
        Set
            If (_Product_ID <> Value) Then
                OnProduct_IDChanging(value)
                ReportPropertyChanging("Product_ID")
                _Product_ID = StructuralObject.SetValidValue(value, "Product_ID")
                ReportPropertyChanged("Product_ID")
                OnProduct_IDChanged()
            End If
        End Set
    End Property

    Private _Product_ID As Global.System.Int32
    Private Partial Sub OnProduct_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnProduct_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Unit_Price() As Global.System.Decimal
        Get
            Return _Unit_Price
        End Get
        Set
            OnUnit_PriceChanging(value)
            ReportPropertyChanging("Unit_Price")
            _Unit_Price = StructuralObject.SetValidValue(value, "Unit_Price")
            ReportPropertyChanged("Unit_Price")
            OnUnit_PriceChanged()
        End Set
    End Property

    Private _Unit_Price As Global.System.Decimal
    Private Partial Sub OnUnit_PriceChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnUnit_PriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Quantity() As Global.System.Int16
        Get
            Return _Quantity
        End Get
        Set
            OnQuantityChanging(value)
            ReportPropertyChanging("Quantity")
            _Quantity = StructuralObject.SetValidValue(value, "Quantity")
            ReportPropertyChanged("Quantity")
            OnQuantityChanged()
        End Set
    End Property

    Private _Quantity As Global.System.Int16
    Private Partial Sub OnQuantityChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnQuantityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Discount() As Global.System.Single
        Get
            Return _Discount
        End Get
        Set
            OnDiscountChanging(value)
            ReportPropertyChanging("Discount")
            _Discount = StructuralObject.SetValidValue(value, "Discount")
            ReportPropertyChanged("Discount")
            OnDiscountChanged()
        End Set
    End Property

    Private _Discount As Global.System.Single
    Private Partial Sub OnDiscountChanging(value As Global.System.Single)
    End Sub

    Private Partial Sub OnDiscountChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Order_Details_FK00", "Products")>
    Public Property Product() As Product
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("Northwind40Model.Order_Details_FK00", "Products").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("Northwind40Model.Order_Details_FK00", "Products").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductReference() As EntityReference(Of Product)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("Northwind40Model.Order_Details_FK00", "Products")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Product)("Northwind40Model.Order_Details_FK00", "Products", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Order_Details_FK01", "Orders")>
    Public Property Order() As Order
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("Northwind40Model.Order_Details_FK01", "Orders").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("Northwind40Model.Order_Details_FK01", "Orders").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OrderReference() As EntityReference(Of Order)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("Northwind40Model.Order_Details_FK01", "Orders")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Order)("Northwind40Model.Order_Details_FK01", "Orders", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Northwind40Model", Name:="Product")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Product
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Product object.
    ''' </summary>
    ''' <param name="product_ID">Initial value of the Product_ID property.</param>
    ''' <param name="product_Name">Initial value of the Product_Name property.</param>
    ''' <param name="discontinued">Initial value of the Discontinued property.</param>
    Public Shared Function CreateProduct(product_ID As Global.System.Int32, product_Name As Global.System.String, discontinued As Global.System.Boolean) As Product
        Dim product as Product = New Product
        product.Product_ID = product_ID
        product.Product_Name = product_Name
        product.Discontinued = discontinued
        Return product
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Product_ID() As Global.System.Int32
        Get
            Return _Product_ID
        End Get
        Set
            If (_Product_ID <> Value) Then
                OnProduct_IDChanging(value)
                ReportPropertyChanging("Product_ID")
                _Product_ID = StructuralObject.SetValidValue(value, "Product_ID")
                ReportPropertyChanged("Product_ID")
                OnProduct_IDChanged()
            End If
        End Set
    End Property

    Private _Product_ID As Global.System.Int32
    Private Partial Sub OnProduct_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnProduct_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Supplier_ID() As Nullable(Of Global.System.Int32)
        Get
            Return _Supplier_ID
        End Get
        Set
            OnSupplier_IDChanging(value)
            ReportPropertyChanging("Supplier_ID")
            _Supplier_ID = StructuralObject.SetValidValue(value, "Supplier_ID")
            ReportPropertyChanged("Supplier_ID")
            OnSupplier_IDChanged()
        End Set
    End Property

    Private _Supplier_ID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnSupplier_IDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnSupplier_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Category_ID() As Nullable(Of Global.System.Int32)
        Get
            Return _Category_ID
        End Get
        Set
            OnCategory_IDChanging(value)
            ReportPropertyChanging("Category_ID")
            _Category_ID = StructuralObject.SetValidValue(value, "Category_ID")
            ReportPropertyChanged("Category_ID")
            OnCategory_IDChanged()
        End Set
    End Property

    Private _Category_ID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCategory_IDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCategory_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Product_Name() As Global.System.String
        Get
            Return _Product_Name
        End Get
        Set
            OnProduct_NameChanging(value)
            ReportPropertyChanging("Product_Name")
            _Product_Name = StructuralObject.SetValidValue(value, false, "Product_Name")
            ReportPropertyChanged("Product_Name")
            OnProduct_NameChanged()
        End Set
    End Property

    Private _Product_Name As Global.System.String
    Private Partial Sub OnProduct_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProduct_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property English_Name() As Global.System.String
        Get
            Return _English_Name
        End Get
        Set
            OnEnglish_NameChanging(value)
            ReportPropertyChanging("English_Name")
            _English_Name = StructuralObject.SetValidValue(value, true, "English_Name")
            ReportPropertyChanged("English_Name")
            OnEnglish_NameChanged()
        End Set
    End Property

    Private _English_Name As Global.System.String
    Private Partial Sub OnEnglish_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEnglish_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Quantity_Per_Unit() As Global.System.String
        Get
            Return _Quantity_Per_Unit
        End Get
        Set
            OnQuantity_Per_UnitChanging(value)
            ReportPropertyChanging("Quantity_Per_Unit")
            _Quantity_Per_Unit = StructuralObject.SetValidValue(value, true, "Quantity_Per_Unit")
            ReportPropertyChanged("Quantity_Per_Unit")
            OnQuantity_Per_UnitChanged()
        End Set
    End Property

    Private _Quantity_Per_Unit As Global.System.String
    Private Partial Sub OnQuantity_Per_UnitChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnQuantity_Per_UnitChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Unit_Price() As Nullable(Of Global.System.Decimal)
        Get
            Return _Unit_Price
        End Get
        Set
            OnUnit_PriceChanging(value)
            ReportPropertyChanging("Unit_Price")
            _Unit_Price = StructuralObject.SetValidValue(value, "Unit_Price")
            ReportPropertyChanged("Unit_Price")
            OnUnit_PriceChanged()
        End Set
    End Property

    Private _Unit_Price As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnUnit_PriceChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnUnit_PriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Units_In_Stock() As Nullable(Of Global.System.Int16)
        Get
            Return _Units_In_Stock
        End Get
        Set
            OnUnits_In_StockChanging(value)
            ReportPropertyChanging("Units_In_Stock")
            _Units_In_Stock = StructuralObject.SetValidValue(value, "Units_In_Stock")
            ReportPropertyChanged("Units_In_Stock")
            OnUnits_In_StockChanged()
        End Set
    End Property

    Private _Units_In_Stock As Nullable(Of Global.System.Int16)
    Private Partial Sub OnUnits_In_StockChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnUnits_In_StockChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Units_On_Order() As Nullable(Of Global.System.Int16)
        Get
            Return _Units_On_Order
        End Get
        Set
            OnUnits_On_OrderChanging(value)
            ReportPropertyChanging("Units_On_Order")
            _Units_On_Order = StructuralObject.SetValidValue(value, "Units_On_Order")
            ReportPropertyChanged("Units_On_Order")
            OnUnits_On_OrderChanged()
        End Set
    End Property

    Private _Units_On_Order As Nullable(Of Global.System.Int16)
    Private Partial Sub OnUnits_On_OrderChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnUnits_On_OrderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Reorder_Level() As Nullable(Of Global.System.Int16)
        Get
            Return _Reorder_Level
        End Get
        Set
            OnReorder_LevelChanging(value)
            ReportPropertyChanging("Reorder_Level")
            _Reorder_Level = StructuralObject.SetValidValue(value, "Reorder_Level")
            ReportPropertyChanged("Reorder_Level")
            OnReorder_LevelChanged()
        End Set
    End Property

    Private _Reorder_Level As Nullable(Of Global.System.Int16)
    Private Partial Sub OnReorder_LevelChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnReorder_LevelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Discontinued() As Global.System.Boolean
        Get
            Return _Discontinued
        End Get
        Set
            OnDiscontinuedChanging(value)
            ReportPropertyChanging("Discontinued")
            _Discontinued = StructuralObject.SetValidValue(value, "Discontinued")
            ReportPropertyChanged("Discontinued")
            OnDiscontinuedChanged()
        End Set
    End Property

    Private _Discontinued As Global.System.Boolean
    Private Partial Sub OnDiscontinuedChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnDiscontinuedChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Products_FK01", "Categories")>
    Public Property Category() As Category
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("Northwind40Model.Products_FK01", "Categories").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("Northwind40Model.Products_FK01", "Categories").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CategoryReference() As EntityReference(Of Category)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("Northwind40Model.Products_FK01", "Categories")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Category)("Northwind40Model.Products_FK01", "Categories", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Order_Details_FK00", "Order_Details")>
     Public Property Order_Details() As EntityCollection(Of Order_Detail)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order_Detail)("Northwind40Model.Order_Details_FK00", "Order_Details")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order_Detail)("Northwind40Model.Order_Details_FK00", "Order_Details", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Products_FK00", "Suppliers")>
    Public Property Supplier() As Supplier
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Supplier)("Northwind40Model.Products_FK00", "Suppliers").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Supplier)("Northwind40Model.Products_FK00", "Suppliers").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SupplierReference() As EntityReference(Of Supplier)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Supplier)("Northwind40Model.Products_FK00", "Suppliers")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Supplier)("Northwind40Model.Products_FK00", "Suppliers", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Northwind40Model", Name:="Shipper")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Shipper
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Shipper object.
    ''' </summary>
    ''' <param name="shipper_ID">Initial value of the Shipper_ID property.</param>
    ''' <param name="company_Name">Initial value of the Company_Name property.</param>
    Public Shared Function CreateShipper(shipper_ID As Global.System.Int32, company_Name As Global.System.String) As Shipper
        Dim shipper as Shipper = New Shipper
        shipper.Shipper_ID = shipper_ID
        shipper.Company_Name = company_Name
        Return shipper
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Shipper_ID() As Global.System.Int32
        Get
            Return _Shipper_ID
        End Get
        Set
            If (_Shipper_ID <> Value) Then
                OnShipper_IDChanging(value)
                ReportPropertyChanging("Shipper_ID")
                _Shipper_ID = StructuralObject.SetValidValue(value, "Shipper_ID")
                ReportPropertyChanged("Shipper_ID")
                OnShipper_IDChanged()
            End If
        End Set
    End Property

    Private _Shipper_ID As Global.System.Int32
    Private Partial Sub OnShipper_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnShipper_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Company_Name() As Global.System.String
        Get
            Return _Company_Name
        End Get
        Set
            OnCompany_NameChanging(value)
            ReportPropertyChanging("Company_Name")
            _Company_Name = StructuralObject.SetValidValue(value, false, "Company_Name")
            ReportPropertyChanged("Company_Name")
            OnCompany_NameChanged()
        End Set
    End Property

    Private _Company_Name As Global.System.String
    Private Partial Sub OnCompany_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCompany_NameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Orders_FK01", "Orders")>
     Public Property Orders() As EntityCollection(Of Order)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("Northwind40Model.Orders_FK01", "Orders")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("Northwind40Model.Orders_FK01", "Orders", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Northwind40Model", Name:="Supplier")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Supplier
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Supplier object.
    ''' </summary>
    ''' <param name="supplier_ID">Initial value of the Supplier_ID property.</param>
    ''' <param name="company_Name">Initial value of the Company_Name property.</param>
    Public Shared Function CreateSupplier(supplier_ID As Global.System.Int32, company_Name As Global.System.String) As Supplier
        Dim supplier as Supplier = New Supplier
        supplier.Supplier_ID = supplier_ID
        supplier.Company_Name = company_Name
        Return supplier
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Supplier_ID() As Global.System.Int32
        Get
            Return _Supplier_ID
        End Get
        Set
            If (_Supplier_ID <> Value) Then
                OnSupplier_IDChanging(value)
                ReportPropertyChanging("Supplier_ID")
                _Supplier_ID = StructuralObject.SetValidValue(value, "Supplier_ID")
                ReportPropertyChanged("Supplier_ID")
                OnSupplier_IDChanged()
            End If
        End Set
    End Property

    Private _Supplier_ID As Global.System.Int32
    Private Partial Sub OnSupplier_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSupplier_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Company_Name() As Global.System.String
        Get
            Return _Company_Name
        End Get
        Set
            OnCompany_NameChanging(value)
            ReportPropertyChanging("Company_Name")
            _Company_Name = StructuralObject.SetValidValue(value, false, "Company_Name")
            ReportPropertyChanged("Company_Name")
            OnCompany_NameChanged()
        End Set
    End Property

    Private _Company_Name As Global.System.String
    Private Partial Sub OnCompany_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCompany_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Contact_Name() As Global.System.String
        Get
            Return _Contact_Name
        End Get
        Set
            OnContact_NameChanging(value)
            ReportPropertyChanging("Contact_Name")
            _Contact_Name = StructuralObject.SetValidValue(value, true, "Contact_Name")
            ReportPropertyChanged("Contact_Name")
            OnContact_NameChanged()
        End Set
    End Property

    Private _Contact_Name As Global.System.String
    Private Partial Sub OnContact_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContact_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Contact_Title() As Global.System.String
        Get
            Return _Contact_Title
        End Get
        Set
            OnContact_TitleChanging(value)
            ReportPropertyChanging("Contact_Title")
            _Contact_Title = StructuralObject.SetValidValue(value, true, "Contact_Title")
            ReportPropertyChanged("Contact_Title")
            OnContact_TitleChanged()
        End Set
    End Property

    Private _Contact_Title As Global.System.String
    Private Partial Sub OnContact_TitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContact_TitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Address() As Global.System.String
        Get
            Return _Address
        End Get
        Set
            OnAddressChanging(value)
            ReportPropertyChanging("Address")
            _Address = StructuralObject.SetValidValue(value, true, "Address")
            ReportPropertyChanged("Address")
            OnAddressChanged()
        End Set
    End Property

    Private _Address As Global.System.String
    Private Partial Sub OnAddressChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, true, "City")
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property

    Private _City As Global.System.String
    Private Partial Sub OnCityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Region() As Global.System.String
        Get
            Return _Region
        End Get
        Set
            OnRegionChanging(value)
            ReportPropertyChanging("Region")
            _Region = StructuralObject.SetValidValue(value, true, "Region")
            ReportPropertyChanged("Region")
            OnRegionChanged()
        End Set
    End Property

    Private _Region As Global.System.String
    Private Partial Sub OnRegionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRegionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Postal_Code() As Global.System.String
        Get
            Return _Postal_Code
        End Get
        Set
            OnPostal_CodeChanging(value)
            ReportPropertyChanging("Postal_Code")
            _Postal_Code = StructuralObject.SetValidValue(value, true, "Postal_Code")
            ReportPropertyChanged("Postal_Code")
            OnPostal_CodeChanged()
        End Set
    End Property

    Private _Postal_Code As Global.System.String
    Private Partial Sub OnPostal_CodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPostal_CodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Country() As Global.System.String
        Get
            Return _Country
        End Get
        Set
            OnCountryChanging(value)
            ReportPropertyChanging("Country")
            _Country = StructuralObject.SetValidValue(value, true, "Country")
            ReportPropertyChanged("Country")
            OnCountryChanged()
        End Set
    End Property

    Private _Country As Global.System.String
    Private Partial Sub OnCountryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCountryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Phone() As Global.System.String
        Get
            Return _Phone
        End Get
        Set
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = StructuralObject.SetValidValue(value, true, "Phone")
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property

    Private _Phone As Global.System.String
    Private Partial Sub OnPhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Fax() As Global.System.String
        Get
            Return _Fax
        End Get
        Set
            OnFaxChanging(value)
            ReportPropertyChanging("Fax")
            _Fax = StructuralObject.SetValidValue(value, true, "Fax")
            ReportPropertyChanged("Fax")
            OnFaxChanged()
        End Set
    End Property

    Private _Fax As Global.System.String
    Private Partial Sub OnFaxChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFaxChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Northwind40Model", "Products_FK00", "Products")>
     Public Property Products() As EntityCollection(Of Product)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Product)("Northwind40Model.Products_FK00", "Products")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Product)("Northwind40Model.Products_FK00", "Products", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region

